# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ScratchMaths
email: daniel.hickmott@uon.edu.au
contact: Daniel Hickmott
baseurl: "/sm-2017"

# Content Pages Paths
resources_path: "/resources"
glossary_path: "/glossary"

# Day 1 Paths
day1_path: "/day1/"
cs_unplugged_path: "/day1/cs_unplugged"
coding_and_maths_path: "/day1/coding_and_maths"
coding_path: "/day1/coding"
teacher_account_path: "/day1/teacher_account"
previous_year_visual_programming_path: "https://cs4s.github.io/ps-2016/day1/visualprogramming/"

# Day 2 Paths
day2_path: "/day2/"
scratch_maths_path: "/day2/scratchmaths"

# Build settings
markdown: kramdown
